### ISSUE TITLE
tokio-runtime-worker panicking

### ISSUE THREAD

**Issue by joolof** [FaisalBinAhmed/MVGFahrinfo#11]
Hi there,
Thanks for providing such a nice tool. I know close to nothing about Rust so this might be a very naive question/issue. The app works perfectly fine but whenever I close it I see the following message:
```
[~] mvgfahrinfo
fetching stations...
thread 'tokio-runtime-worker' panicked at 'failed to send tick event: SendError { .. }', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mvgfahrinfo-1.1.0/src/event.rs:50:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Did  I do something wrong when installing it using binstall?
Cheers

**Comment by FaisalBinAhmed** [comment]
Hi @joolof,
thanks for opening up this issue and notifying me. You didn't do anything wrong, I also see this message after quiting.
This message is harmless and happens because the event thread is unable to send the last tick event because the receiver is shut down when the app is closing. I might handle it better at a later release but this isn't an issue.
